### ISSUE TITLE
align.wave behaviour

### ISSUE THREAD

**Issue by Stephentyndel** [p-rocha/SoundShape#1]
Hello,

I was just trying to get the align.wave function to work, but keep getting the following error message:

> Error in align.wave(wav.at = wd, wav.to = "Aligned", time.length = 0.75,  : 
>   Time percentage is too large. Consider a smaller value of 'time.perc'
> 

This appears to occur no matter what the time.length is or what the time.perc value is listed as. I was wondering if you could provide any more feedback on this error message. Thanks!

**Comment by p-rocha** [comment]
Hello @Stephentyndel,

`time.perc` is relative to the `time.length`. The first has to be very small (i.e. default `time.perc = 0.005`), whereas the latter should be greater than the longest duration sound within your sample. 
The error occurs whenever the aligned sound overlaps the edges of your sound window, thus leading to loss of acoustic information. In order to solve it, consider a smaller value of `time.perc`, _or_ a higher `time.length`. 

I suggest that you leave the default `time.perc` and worry only about the `time.length`.

Cheers,

Pedro
